/**
 * Regenerate the checked-in legendary image manifests used by the picker and evaluator.
 *
 * Usage:
 * - Run `yarn generateLegendaryImageMaps`
 * - Review the generated files in `src/legendaryRating/components/LegendaryPicker/generated`
 */

import fs from "node:fs";
import path from "node:path";
import mkdirp from "mkdirp";
import {
    armorArchetypes,
    helmetArchetypes,
    melee1hArchetypes,
    melee2hArchetypes,
    rangedArchetypes,
    shieldArchetypes,
} from "../src/legendaryRating/data/archetypes";
import type { ArchetypeBase, CategoryId } from "../src/legendaryRating/types/models";

interface CategoryConfig {
    archetypes: Record<string, ArchetypeBase>;
    categoryId: CategoryId;
    folderName: string;
}

interface ImageFileEntry {
    baseName: string;
    relativePath: string;
}

const generatedDirectory = path.resolve(__dirname, "../src/legendaryRating/components/LegendaryPicker/generated");
const imagesDirectory = path.resolve(__dirname, "../src/legendaryRating/images");
const generatedImageImportPrefix = "../../../images";
const scriptName = path.basename(__filename);

const categoryConfigs: CategoryConfig[] = [
    { categoryId: "oneHanded", folderName: "melee1h", archetypes: melee1hArchetypes },
    { categoryId: "twoHanded", folderName: "melee2h", archetypes: melee2hArchetypes },
    { categoryId: "ranged", folderName: "ranged", archetypes: rangedArchetypes },
    { categoryId: "shield", folderName: "shield", archetypes: shieldArchetypes },
    { categoryId: "helmet", folderName: "helmet", archetypes: helmetArchetypes },
    { categoryId: "armor", folderName: "armor", archetypes: armorArchetypes },
];

const toIdentifier = (value: string) => {
    return `image_${value.replace(/[^a-zA-Z0-9_$]/g, "_")}`;
};

const getGeneratedFileHeader = () => {
    return [`/* This file is generated by scripts/${scriptName}. */`, ""].join("\n");
};

const getReferencedImageKeys = (archetypes: Record<string, ArchetypeBase>) => {
    const imageKeys = Object.values(archetypes).flatMap((archetype) => [
        archetype.imageName,
        ...archetype.alternateImages,
    ]);
    return Array.from(new Set(imageKeys)).sort((left, right) => left.localeCompare(right));
};

const getImageFilesByBaseName = (folderName: string) => {
    const categoryDirectory = path.join(imagesDirectory, folderName);
    const fileNames = fs
        .readdirSync(categoryDirectory)
        .filter((fileName) => fileName.endsWith(".png"))
        .sort();

    return fileNames.reduce<Record<string, ImageFileEntry>>((accumulator, fileName) => {
        const baseName = fileName.replace(/\.png$/, "");
        accumulator[baseName] = {
            baseName,
            relativePath: `${generatedImageImportPrefix}/${folderName}/${fileName}`,
        };
        return accumulator;
    }, {});
};

const getPreviewCandidates = (imageKey: string) => {
    const candidates = [
        imageKey.endsWith("_70x70") ? imageKey.replace(/_70x70$/, "_140x70") : undefined,
        imageKey.endsWith("_70x70") ? imageKey.replace(/_70x70$/, "") : undefined,
        imageKey.startsWith("icon_") ? imageKey.replace(/^icon_/, "inventory_") : undefined,
        imageKey,
    ].filter((candidate): candidate is string => Boolean(candidate));

    return Array.from(new Set(candidates));
};

const resolveRequiredImageFile = (
    imageKey: string,
    imageFilesByBaseName: Record<string, ImageFileEntry>,
    errorContext: string,
) => {
    const matchedImageFile = imageFilesByBaseName[imageKey];
    if (!matchedImageFile) {
        throw new Error(`Missing ${errorContext} image "${imageKey}"`);
    }

    return matchedImageFile;
};

const resolvePreviewImageFile = (imageKey: string, imageFilesByBaseName: Record<string, ImageFileEntry>) => {
    const previewImageKey = getPreviewCandidates(imageKey).find((candidate) => imageFilesByBaseName[candidate]);
    if (!previewImageKey) {
        throw new Error(`Missing preview image for "${imageKey}"`);
    }

    return imageFilesByBaseName[previewImageKey];
};

const buildModuleSource = (variableName: string, entries: Array<{ imageFile: ImageFileEntry; imageKey: string }>) => {
    const imports = entries
        .map(({ imageFile }) => imageFile)
        .filter((imageFile, index, allImageFiles) => {
            return allImageFiles.findIndex((candidate) => candidate.baseName === imageFile.baseName) === index;
        })
        .sort((left, right) => left.baseName.localeCompare(right.baseName))
        .map((imageFile) => `import ${toIdentifier(imageFile.baseName)} from "${imageFile.relativePath}";`)
        .join("\n");

    const objectEntries = entries
        .sort((left, right) => left.imageKey.localeCompare(right.imageKey))
        .map(({ imageFile, imageKey }) => `    ${imageKey}: ${toIdentifier(imageFile.baseName)},`)
        .join("\n");

    return [
        getGeneratedFileHeader(),
        imports,
        "",
        'import { LegendaryItemImageMap } from "../legendaryItemImageMap";',
        "",
        `const ${variableName}: LegendaryItemImageMap = {`,
        objectEntries,
        "};",
        "",
        `export default ${variableName};`,
        "",
    ].join("\n");
};

mkdirp.sync(generatedDirectory);

for (const categoryConfig of categoryConfigs) {
    const imageKeys = getReferencedImageKeys(categoryConfig.archetypes);
    const imageFilesByBaseName = getImageFilesByBaseName(categoryConfig.folderName);

    const thumbnailEntries = imageKeys.map((imageKey) => ({
        imageKey,
        imageFile: resolveRequiredImageFile(imageKey, imageFilesByBaseName, "thumbnail"),
    }));

    const previewEntries = imageKeys.map((imageKey) => ({
        imageKey,
        imageFile: resolvePreviewImageFile(imageKey, imageFilesByBaseName),
    }));

    const thumbnailFile = path.join(generatedDirectory, `legendaryThumbnailMap.${categoryConfig.categoryId}.ts`);
    const previewFile = path.join(generatedDirectory, `legendaryPreviewMap.${categoryConfig.categoryId}.ts`);

    fs.writeFileSync(thumbnailFile, buildModuleSource("legendaryThumbnailMap", thumbnailEntries));
    fs.writeFileSync(previewFile, buildModuleSource("legendaryPreviewMap", previewEntries));

    console.log(
        `Generated ${path.relative(path.resolve(__dirname, ".."), thumbnailFile)} and ${path.relative(path.resolve(__dirname, ".."), previewFile)}`,
    );
}
