/**
 * So this isn't saved in redux, and is instead a singleton.
 * And you know what? That's ok!
 *
 * This is used as a convenient place to temporarily store perk data during compression
 */
export let perkBinary = {
    fastAdaption: 0,
    cripplingStrikes: 0,
    colossus: 0,
    nineLives: 0,
    bagsAndBelts: 0,
    pathfinder: 0,
    adrenaline: 0,
    recover: 0,
    student: 0,
    executioner: 0,
    bullseye: 0,
    dodge: 0,
    fortifiedMind: 0,
    resilient: 0,
    steelBrow: 0,
    quickHands: 0,
    gifted: 0,
    backstabber: 0,
    anticipation: 0,
    shieldExpert: 0,
    brawny: 0,
    relentless: 0,
    rotation: 0,
    rally: 0,
    taunt: 0,
    maceMastery: 0,
    flailMastery: 0,
    hammerMastery: 0,
    axeMastery: 0,
    cleaverMastery: 0,
    swordMastery: 0,
    daggerMastery: 0,
    polearmMastery: 0,
    spearMastery: 0,
    crossbowMastery: 0,
    bowMastery: 0,
    throwingMastery: 0,
    reachAdvantage: 0,
    overwhelm: 0,
    loneWolf: 0,
    underdog: 0,
    footwork: 0,
    berserk: 0,
    headhunter: 0,
    nimble: 0,
    battleForged: 0,
    fearsome: 0,
    duelist: 0,
    killingFrenzy: 0,
    indomitable: 0,
};