export const idsByItem: { [key: string]: string; } = {
    "Ancient Sword": "AB",
    "Antler Cleaver": "AC",
    "Arming Sword": "AD",
    "Axehammer": "AE",
    "Bardiche": "AF",
    "Battle Whip": "AG",
    "Billhook": "AH",
    "Ancient Bladed Pike": "AI",
    "Bludgeon": "AJ",
    "Blunt Cleaver": "AK",
    "Boar Spear": "AL",
    "Broken Ancient Sword": "AM",
    "Broken Ancient Bladed Pike": "AN",
    "Butcher's Cleaver": "AO",
    "Claw Club": "AP",
    "Crossbow": "AQ",
    "Crude Axe": "AR",
    "Crypt Cleaver": "AS",
    "Dagger": "AT",
    "Drum": "AU",
    "Falchion": "AV",
    "Falx": "AW",
    "Fencing Sword": "AX",
    "Fighting Axe": "AY",
    "Fighting Spear": "AZ",
    "Flail": "Aa",
    "Boondock Bow": "Ab",
    "Spiked Impaler": "Ac",
    "Cruel Falchion": "Ad",
    "Reinforced Boondock Bow": "Ae",
    "Notched Blade": "Af",
    "Jagged Pike": "Ag",
    "Goblin Skewer": "Ah",
    "Bundle of Spiked Bolas": "Ai",
    "Gnarly Staff": "Aj",
    "Goedendag": "Ak",
    "Greataxe": "Al",
    "Greatsword": "Am",
    "Handaxe": "An",
    "Hatchet": "Ao",
    "Heavy Crossbow": "Ap",
    "Bundle of Heavy Javelins": "Aq",
    "Heavy Rusty Axe": "Ar",
    "Bundle of Heavy Throwing Axes": "As",
    "Hooked Blade": "At",
    "Hunting Bow": "Au",
    "Bundle of Javelins": "Av",
    "Khopesh": "Aw",
    "Knife": "Ax",
    "Reproach of the Old Gods": "Ay",
    "Light Crossbow": "Az",
    "Longaxe": "A0",
    "Longsword": "A1",
    "Lute": "A2",
    "Masterwork Bow": "A3",
    "Military Cleaver": "A4",
    "Military Pick": "A5",
    "Militia Spear": "A6",
    "Morning Star": "A7",
    "Noble Sword": "A8",
    "Obsidian Dagger": "A9",
    "Head Splitter": "A+",
    "Man Splitter": "A/",
    "Head Chopper derp": "BA",
    "Berserk Chain": "BB",
    "Bundle of Crude Javelins": "BC",
    "Cudgel": "BD",
    "Tree Limb": "BE",
    "Pickaxe": "BF",
    "Pike": "BG",
    "Pitchfork": "BH",
    "Battle Standard": "BI",
    "Polehammer": "BJ",
    "Reinforced Wooden Flail": "BK",
    "Rhomphaia": "BL",
    "Rondel Dagger": "BM",
    "Rusty Warblade": "BN",
    "Scimitar": "BO",
    "Scramasax": "BP",
    "Shamshir": "BQ",
    "Shortsword": "BR",
    "Short Bow": "BS",
    "Two-Handed Skull Hammer": "BT",
    "Spetum": "BU",
    "Staff Sling": "BV",
    "Thorned Whip": "BW",
    "Three-Headed Flail": "BX",
    "Bundle of Throwing Axes": "BY",
    "Throwing Spear": "BZ",
    "Two-handed Flail": "Ba",
    "Two-Handed Flanged Mace": "Bb",
    "Two-Handed Hammer": "Bc",
    "Two-Handed Mace": "Bd",
    "Two-Handed Spiked Mace": "Be",
    "Two-handed Wooden Flail": "Bf",
    "Two-Handed Mallet": "Bg",
    "Warbrand": "Bh",
    "Warfork": "Bi",
    "Warhammer": "Bj",
    "Warscythe": "Bk",
    "War Bow": "Bl",
    "Winged Mace": "Bm",
    "Wonky Bow": "Bn",
    "Woodcutter's Axe": "Bo",
    "Wooden Flail": "Bp",
    "Wooden Stick": "Bq",
    "Acid Flask": "Br",
    "Flask of Blessed Water": "Bs",
    "Reinforced Throwing Net": "Bt",
    "Throwing Net": "Bu",
    "Ancient Auxiliary Shield": "Bv",
    "Buckler": "Bw",
    "Ancient Coffin Shield": "Bx",
    "Kraken Shield": "By",
    "Lindwurm Shield": "Bz",
    "Living Tree Shield": "B0",
    "Reinforced Skirmisher Shield": "B1",
    "Wooden Skirmisher Shield": "B2",
    "Heater Shield": "B3",
    "Kite Shield": "B4",
    "Heavy Metal Shield": "B5",
    "Feral Shield": "B6",
    "Ancient Tower Shield": "B7",
    "Wooden Shield": "B8",
    "Old Wooden Shield": "B9",
    "Decayed Heater Shield": "B+",
    "Worn Kite Shield": "B/",
    "Aketon Cap derp": "CA",
    "Ancient Honor Guard Helmet": "CB",
    "Ancient Household Helmet": "CC",
    "Ancient Legionary Helmet": "CD",
    "Barbute Helmet": "CE",
    "Bascinet with Mail": "CF",
    "Bear Headpiece": "CG",
    "Beastmaster's Headpiece": "CH",
    "Closed Flat Top Helmet": "CI",
    "Closed Flat Top with Mail": "CJ",
    "Closed and Padded Flat Top": "CK",
    "Closed Mail Coif": "CL",
    "Closed Scrap Metal Helmet": "CM",
    "Conic Helmet with Closed Mail": "CN",
    "Conic Helmet with Faceguard": "CO",
    "Crude Faceguard Helmet": "CP",
    "Crude Metal Helmet": "CQ",
    "Cultist Hood": "CR",
    "Cultist Leather Hood": "CS",
    "Dark Cowl": "CT",
    "Decayed Closed Flat Top with Mail": "CU",
    "Covered Decayed Closed Flat Top with Mail": "CV",
    "Decayed Full Helm": "CW",
    "Decayed Great Helm": "CX",
    "Padded Dented Nasal Helmet": "CY",
    "The Emperor's Countenance": "CZ",
    "Decorated Full Helm": "Ca",
    "Feathered Hat": "Cb",
    "Flat Top Helmet": "Cc",
    "Flat Top with Closed Mail": "Cd",
    "Flat Top with Mail": "Ce",
    "Full Aketon Cap": "Cf",
    "Full Helm": "Cg",
    "Full Leather Cap": "Ch",
    "Zweihander's Helmet": "Ci",
    "Duelist's Hat": "Cj",
    "Headscarf": "Ck",
    "Heavy Horned Plate Helmet": "Cl",
    "Hood": "Cm",
    "Hunter's Hat": "Cn",
    "Helmet of the Ijirok": "Co",
    "Jester's Hat": "Cp",
    "Kettle hat": "Cq",
    "Kettle Hat with Closed Mail": "Cr",
    "Kettle Hat with Mail": "Cs",
    "Leather Headband": "Ct",
    "Leather Helmet": "Cu",
    "Mail Coif": "Cv",
    "Glimpse of Davkul": "Cw",
    "Mouth Piece": "Cx",
    "Nasal Helmet": "Cy",
    "Nasal Helmet with Closed Mail": "Cz",
    "Nasal Helmet with Mail": "C0",
    "Nasal Helmet With Rusty Mail": "C1",
    "Nordic Helmet": "C2",
    "Nordic Helmet with Closed Mail": "C3",
    "Open Leather Cap": "C4",
    "Padded Flat Top Helmet": "C5",
    "Padded Kettle hat": "C6",
    "Padded Nasal Helmet": "C7",
    "Reinforced Mail Coif": "C8",
    "Rusty Mail Coif": "C9",
    "Sallet Helmet": "C+",
    "Steppe Helmet with Mail": "C/",
    "Straw Hat derp": "DA",
    "Witchhunter's Hat": "DB",
    "Wizard's Hat": "DC",
    "Antidote": "DD",
    "Bandages": "DE",
    "Strange Mushrooms": "DF",
    "Cat Potion": "DG",
    "Iron Will Potion": "DH",
    "Lionheart Potion": "DI",
    "Night Owl Elixir": "DJ",
    "Goblin Poison": "DK",
    "Second Wind Potion": "DL",
    "Poisoned Oil": "DM",
    "Ancient Breastplate": "DN",
    "Ancient Double Layer Mail": "DO",
    "Ancient Mail": "DP",
    "Ancient Plated Mail Hauberk": "DQ",
    "Ancient Plated Scale Hauberk": "DR",
    "Ancient Plate Harness": "DS",
    "Ancient Scale Coat": "DT",
    "Ancient Scale Harness": "DU",
    "Animal Hide Armor": "DV",
    "Apron": "DW",
    "Aspect of Davkul": "DX",
    "Basic Mail Shirt": "DY",
    "Blotched Gambeson": "DZ",
    "Butcher's Apron": "Da",
    "Coat of Plates": "Db",
    "Coat of Scales": "Dc",
    "Cultist Leather Robe": "Dd",
    "Decayed Coat of Plates": "De",
    "Decayed Coat of Scales": "Df",
    "Decayed Reinforced Mail Hauberk": "Dg",
    "The Emperor's Armor": "Dh",
    "Footman's Armor": "Di",
    "Gambeson": "Dj",
    "Heavy Iron Armor": "Dk",
    "Heavy Lamellar Armor": "Dl",
    "Heraldic Mail": "Dm",
    "Hide and Bone Armor": "Dn",
    "Armor of the Ijirok": "Do",
    "Lamellar Harness": "Dp",
    "Leather Lamellar Armor": "Dq",
    "Leather Scale Armor": "Dr",
    "Leather Tunic": "Ds",
    "Leather Wraps": "Dt",
    "Light Scale Armor": "Du",
    "Linen Tunic": "Dv",
    "Mail Hauberk": "Dw",
    "Mail Shirt": "Dx",
    "Monk's Robe": "Dy",
    "Noble Mail": "Dz",
    "Noble Tunic": "D0",
    "Padded Leather": "D1",
    "Padded Surcoat": "D2",
    "Patched Mail Shirt": "D3",
    "Dark Rugged Surcoat": "D4",
    "Rugged Surcoat": "D5",
    "Reinforced Animal Hide Armor": "D6",
    "Reinforced Mail Hauberk": "D7",
    "Rugged Scale Armor": "D8",
    "Sackcloth": "D9",
    "Scale Armor": "D+",
    "Scrap Metal Armor": "D/",
    "Sellsword's Armor derp": "EA",
    "Tattered Sackcloth": "EB",
    "Dark Thick Tunic": "EC",
    "Thick Furs": "ED",
    "Thick Plated Barbarian Armor": "EE",
    "Thick Tunic": "EF",
    "Direwolf Hide Armor": "EG",
    "Direwolf Mail Armor": "EH",
    "Wizard's Robe": "EI",
    "Worn Mail Shirt": "EJ",
    "Large Quiver of Arrows": "EK",
    "Large Quiver of Bolts": "EL",
    "Quiver of Arrows": "EM",
    "Quiver of Bolts": "EN",
    "Alp Trophy Necklace": "EO",
    "Armored Wardog": "EP",
    "Armored Warhound": "EQ",
    "Cursed Crystal Skull": "ER",
    "Falcon": "ES",
    "Nachzehrer Trophy Necklace": "ET",
    "Goblin Trophy": "EU",
    "Heavily Armored Wardog": "EV",
    "Heavily Armored Warhound": "EW",
    "Hexen Trophy Necklace": "EX",
    "Orc Trophy": "EY",
    "Sergeant's Sash": "EZ",
    "Undead Trophy": "Ea",
    "Wardog": "Eb",
    "Unleash Warhound": "Ec",
    "Warwolf": "Ed",
    "Composite Bow": "Ee",
    "Fire Lance": "Ef",
    "Handgonne": "Eg",
    "Heavy Southern Mace": "Eh",
    "Light Southern Mace": "Ei",
    "Nomad Mace": "Ej",
    "Nomad Sling": "Ek",
    "Polemace": "El",
    "Qatal Dagger": "Em",
    "Saif": "En",
    "Swordlance": "Eo",
    "Two-Handed Saif": "Ep",
    "Two-Handed Scimitar": "Eq",
    "Flash Pot": "Er",
    "Fire Pot": "Es",
    "Smoke Pot": "Et",
    "Assassin's Face Mask": "Eu",
    "Assassin's Head Wrap": "Ev",
    "Blade Dancer's Head Wrap": "Ew",
    "Desert Stalker's Head Wrap": "Ex",
    "Engineer's Hat": "Ey",
    "Gladiator Helmet": "Ez",
    "Gunner's Hat": "E0",
    "Heavy Lamellar Helmet": "E1",
    "Leather Head Wrap": "E2",
    "Nomad Head Wrap": "E3",
    "Nomad Leather Cap": "E4",
    "Nomad Light Helmet": "E5",
    "Nomad Reinforced Helmet": "E6",
    "Southern Head Wrap": "E7",
    "Southern Helmet with Coif": "E8",
    "Spiked Skull Cap with Mail": "E9",
    "Turban Helmet": "E+",
    "Wrapped Southern Helmet": "E/",
    "Large Powder Bag": "FA",
    "Powder Bag": "FB",
    "Assassin's Robe": "FC",
    "Cloth Sash": "FD",
    "Gladiator Harness": "FE",
    "Leather Nomad Robe": "FF",
    "Linothorax": "FG",
    "Mail with Lamellar Plating": "FH",
    "Nomad Robe": "FI",
    "Padded Mail and Lamellar Hauberk": "FJ",
    "Padded Vest": "FK",
    "Plated Nomad Mail": "FL",
    "Southern Long Mail Shirt with Padding": "FM",
    "Southern Mail Shirt": "FN",
    "Stitched Nomad Armor": "FO",
    "Thick Nomad Robe": "FP",
    "Gilder's Embrace": "FQ",
    "Sipar Shield": "FR",
    "Adarga Shield": "FS",
    "Head Chopper": "FT",
    "Aketon Cap": "FU",
    "Straw Hat": "FV",
    "Sellsword's Armor": "FW",
};