export const itemsById: { [key: string]: string; } = {
    "AB": "Ancient Sword",
    "AC": "Antler Cleaver",
    "AD": "Arming Sword",
    "AE": "Axehammer",
    "AF": "Bardiche",
    "AG": "Battle Whip",
    "AH": "Billhook",
    "AI": "Ancient Bladed Pike",
    "AJ": "Bludgeon",
    "AK": "Blunt Cleaver",
    "AL": "Boar Spear",
    "AM": "Broken Ancient Sword",
    "AN": "Broken Ancient Bladed Pike",
    "AO": "Butcher's Cleaver",
    "AP": "Claw Club",
    "AQ": "Crossbow",
    "AR": "Crude Axe",
    "AS": "Crypt Cleaver",
    "AT": "Dagger",
    "AU": "Drum",
    "AV": "Falchion",
    "AW": "Falx",
    "AX": "Fencing Sword",
    "AY": "Fighting Axe",
    "AZ": "Fighting Spear",
    "Aa": "Flail",
    "Ab": "Boondock Bow",
    "Ac": "Spiked Impaler",
    "Ad": "Cruel Falchion",
    "Ae": "Reinforced Boondock Bow",
    "Af": "Notched Blade",
    "Ag": "Jagged Pike",
    "Ah": "Goblin Skewer",
    "Ai": "Bundle of Spiked Bolas",
    "Aj": "Gnarly Staff",
    "Ak": "Goedendag",
    "Al": "Greataxe",
    "Am": "Greatsword",
    "An": "Handaxe",
    "Ao": "Hatchet",
    "Ap": "Heavy Crossbow",
    "Aq": "Bundle of Heavy Javelins",
    "Ar": "Heavy Rusty Axe",
    "As": "Bundle of Heavy Throwing Axes",
    "At": "Hooked Blade",
    "Au": "Hunting Bow",
    "Av": "Bundle of Javelins",
    "Aw": "Khopesh",
    "Ax": "Knife",
    "Ay": "Reproach of the Old Gods",
    "Az": "Light Crossbow",
    "A0": "Longaxe",
    "A1": "Longsword",
    "A2": "Lute",
    "A3": "Masterwork Bow",
    "A4": "Military Cleaver",
    "A5": "Military Pick",
    "A6": "Militia Spear",
    "A7": "Morning Star",
    "A8": "Noble Sword",
    "A9": "Obsidian Dagger",
    "A+": "Head Splitter",
    "A/": "Man Splitter",
    "": "Sellsword's Armor",
    "BB": "Berserk Chain",
    "BC": "Bundle of Crude Javelins",
    "BD": "Cudgel",
    "BE": "Tree Limb",
    "BF": "Pickaxe",
    "BG": "Pike",
    "BH": "Pitchfork",
    "BI": "Battle Standard",
    "BJ": "Polehammer",
    "BK": "Reinforced Wooden Flail",
    "BL": "Rhomphaia",
    "BM": "Rondel Dagger",
    "BN": "Rusty Warblade",
    "BO": "Scimitar",
    "BP": "Scramasax",
    "BQ": "Shamshir",
    "BR": "Shortsword",
    "BS": "Short Bow",
    "BT": "Two-Handed Skull Hammer",
    "BU": "Spetum",
    "BV": "Staff Sling",
    "BW": "Thorned Whip",
    "BX": "Three-Headed Flail",
    "BY": "Bundle of Throwing Axes",
    "BZ": "Throwing Spear",
    "Ba": "Two-handed Flail",
    "Bb": "Two-Handed Flanged Mace",
    "Bc": "Two-Handed Hammer",
    "Bd": "Two-Handed Mace",
    "Be": "Two-Handed Spiked Mace",
    "Bf": "Two-handed Wooden Flail",
    "Bg": "Two-Handed Mallet",
    "Bh": "Warbrand",
    "Bi": "Warfork",
    "Bj": "Warhammer",
    "Bk": "Warscythe",
    "Bl": "War Bow",
    "Bm": "Winged Mace",
    "Bn": "Wonky Bow",
    "Bo": "Woodcutter's Axe",
    "Bp": "Wooden Flail",
    "Bq": "Wooden Stick",
    "Br": "Acid Flask",
    "Bs": "Flask of Blessed Water",
    "Bt": "Reinforced Throwing Net",
    "Bu": "Throwing Net",
    "Bv": "Ancient Auxiliary Shield",
    "Bw": "Buckler",
    "Bx": "Ancient Coffin Shield",
    "By": "Kraken Shield",
    "Bz": "Lindwurm Shield",
    "B0": "Living Tree Shield",
    "B1": "Reinforced Skirmisher Shield",
    "B2": "Wooden Skirmisher Shield",
    "B3": "Heater Shield",
    "B4": "Kite Shield",
    "B5": "Heavy Metal Shield",
    "B6": "Feral Shield",
    "B7": "Ancient Tower Shield",
    "B8": "Wooden Shield",
    "B9": "Old Wooden Shield",
    "B+": "Decayed Heater Shield",
    "B/": "Worn Kite Shield",
    "CB": "Ancient Honor Guard Helmet",
    "CC": "Ancient Household Helmet",
    "CD": "Ancient Legionary Helmet",
    "CE": "Barbute Helmet",
    "CF": "Bascinet with Mail",
    "CG": "Bear Headpiece",
    "CH": "Beastmaster's Headpiece",
    "CI": "Closed Flat Top Helmet",
    "CJ": "Closed Flat Top with Mail",
    "CK": "Closed and Padded Flat Top",
    "CL": "Closed Mail Coif",
    "CM": "Closed Scrap Metal Helmet",
    "CN": "Conic Helmet with Closed Mail",
    "CO": "Conic Helmet with Faceguard",
    "CP": "Crude Faceguard Helmet",
    "CQ": "Crude Metal Helmet",
    "CR": "Cultist Hood",
    "CS": "Cultist Leather Hood",
    "CT": "Dark Cowl",
    "CU": "Decayed Closed Flat Top with Mail",
    "CV": "Covered Decayed Closed Flat Top with Mail",
    "CW": "Decayed Full Helm",
    "CX": "Decayed Great Helm",
    "CY": "Padded Dented Nasal Helmet",
    "CZ": "The Emperor's Countenance",
    "Ca": "Decorated Full Helm",
    "Cb": "Feathered Hat",
    "Cc": "Flat Top Helmet",
    "Cd": "Flat Top with Closed Mail",
    "Ce": "Flat Top with Mail",
    "Cf": "Full Aketon Cap",
    "Cg": "Full Helm",
    "Ch": "Full Leather Cap",
    "Ci": "Zweihander's Helmet",
    "Cj": "Duelist's Hat",
    "Ck": "Headscarf",
    "Cl": "Heavy Horned Plate Helmet",
    "Cm": "Hood",
    "Cn": "Hunter's Hat",
    "Co": "Helmet of the Ijirok",
    "Cp": "Jester's Hat",
    "Cq": "Kettle hat",
    "Cr": "Kettle Hat with Closed Mail",
    "Cs": "Kettle Hat with Mail",
    "Ct": "Leather Headband",
    "Cu": "Leather Helmet",
    "Cv": "Mail Coif",
    "Cw": "Glimpse of Davkul",
    "Cx": "Mouth Piece",
    "Cy": "Nasal Helmet",
    "Cz": "Nasal Helmet with Closed Mail",
    "C0": "Nasal Helmet with Mail",
    "C1": "Nasal Helmet With Rusty Mail",
    "C2": "Nordic Helmet",
    "C3": "Nordic Helmet with Closed Mail",
    "C4": "Open Leather Cap",
    "C5": "Padded Flat Top Helmet",
    "C6": "Padded Kettle hat",
    "C7": "Padded Nasal Helmet",
    "C8": "Reinforced Mail Coif",
    "C9": "Rusty Mail Coif",
    "C+": "Sallet Helmet",
    "C/": "Steppe Helmet with Mail",
    "DB": "Witchhunter's Hat",
    "DC": "Wizard's Hat",
    "DD": "Antidote",
    "DE": "Bandages",
    "DF": "Strange Mushrooms",
    "DG": "Cat Potion",
    "DH": "Iron Will Potion",
    "DI": "Lionheart Potion",
    "DJ": "Night Owl Elixir",
    "DK": "Goblin Poison",
    "DL": "Second Wind Potion",
    "DM": "Poisoned Oil",
    "DN": "Ancient Breastplate",
    "DO": "Ancient Double Layer Mail",
    "DP": "Ancient Mail",
    "DQ": "Ancient Plated Mail Hauberk",
    "DR": "Ancient Plated Scale Hauberk",
    "DS": "Ancient Plate Harness",
    "DT": "Ancient Scale Coat",
    "DU": "Ancient Scale Harness",
    "DV": "Animal Hide Armor",
    "DW": "Apron",
    "DX": "Aspect of Davkul",
    "DY": "Basic Mail Shirt",
    "DZ": "Blotched Gambeson",
    "Da": "Butcher's Apron",
    "Db": "Coat of Plates",
    "Dc": "Coat of Scales",
    "Dd": "Cultist Leather Robe",
    "De": "Decayed Coat of Plates",
    "Df": "Decayed Coat of Scales",
    "Dg": "Decayed Reinforced Mail Hauberk",
    "Dh": "The Emperor's Armor",
    "Di": "Footman's Armor",
    "Dj": "Gambeson",
    "Dk": "Heavy Iron Armor",
    "Dl": "Heavy Lamellar Armor",
    "Dm": "Heraldic Mail",
    "Dn": "Hide and Bone Armor",
    "Do": "Armor of the Ijirok",
    "Dp": "Lamellar Harness",
    "Dq": "Leather Lamellar Armor",
    "Dr": "Leather Scale Armor",
    "Ds": "Leather Tunic",
    "Dt": "Leather Wraps",
    "Du": "Light Scale Armor",
    "Dv": "Linen Tunic",
    "Dw": "Mail Hauberk",
    "Dx": "Mail Shirt",
    "Dy": "Monk's Robe",
    "Dz": "Noble Mail",
    "D0": "Noble Tunic",
    "D1": "Padded Leather",
    "D2": "Padded Surcoat",
    "D3": "Patched Mail Shirt",
    "D4": "Dark Rugged Surcoat",
    "D5": "Rugged Surcoat",
    "D6": "Reinforced Animal Hide Armor",
    "D7": "Reinforced Mail Hauberk",
    "D8": "Rugged Scale Armor",
    "D9": "Sackcloth",
    "D+": "Scale Armor",
    "D/": "Scrap Metal Armor",
    "EB": "Tattered Sackcloth",
    "EC": "Dark Thick Tunic",
    "ED": "Thick Furs",
    "EE": "Thick Plated Barbarian Armor",
    "EF": "Thick Tunic",
    "EG": "Direwolf Hide Armor",
    "EH": "Direwolf Mail Armor",
    "EI": "Wizard's Robe",
    "EJ": "Worn Mail Shirt",
    "EK": "Large Quiver of Arrows",
    "EL": "Large Quiver of Bolts",
    "EM": "Quiver of Arrows",
    "EN": "Quiver of Bolts",
    "EO": "Alp Trophy Necklace",
    "EP": "Armored Wardog",
    "EQ": "Armored Warhound",
    "ER": "Cursed Crystal Skull",
    "ES": "Falcon",
    "ET": "Nachzehrer Trophy Necklace",
    "EU": "Goblin Trophy",
    "EV": "Heavily Armored Wardog",
    "EW": "Heavily Armored Warhound",
    "EX": "Hexen Trophy Necklace",
    "EY": "Orc Trophy",
    "EZ": "Sergeant's Sash",
    "Ea": "Undead Trophy",
    "Eb": "Wardog",
    "Ec": "Unleash Warhound",
    "Ed": "Warwolf"
};